## **ANN Model**

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [14]:
# Data Visualization
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
%matplotlib inline

# Pre-processing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder

# Model
import keras
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras.optimizers import Adam         # Adaptive Moment Estimation
from keras.layers import LeakyReLU

# Metrics
from sklearn.metrics import confusion_matrix, accuracy_score

In [15]:
data = pd.read_csv('drive/My Drive/Colab Notebooks/csv_dataset/Churn_Modelling.csv')
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [16]:
X = data.iloc[:, 3:-1].values
y = data.iloc[:, -1].values

Convert the gender where instead of "Female" and "Male", we make it 0 and 1 using label encoder function.

In [17]:
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [18]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [19]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Split the training and testing datasets. (80/20) and transform it

In [188]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 20)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## **Building the Model**

In [189]:
# Initialize the ANN model
ann = tf.keras.models.Sequential()

# Input layer & first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='LeakyReLU'))
# Second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='LeakyReLU'))
ann.add(tf.keras.layers.Dense(units=6, activation='LeakyReLU'))
ann.add(tf.keras.layers.Dense(units=6, activation='LeakyReLU'))
# Output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Compile the model
ann.compile(optimizer= 'adagrad', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [190]:
# train the model
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6946 - accuracy: 0.5961
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6660 - accuracy: 0.6967
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6497 - accuracy: 0.7483
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6370 - accuracy: 0.7707
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6263 - accuracy: 0.7818
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6165 - accuracy: 0.7883
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6075 - accuracy: 0.7908
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5990 - accuracy: 0.7924
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5910 - accuracy: 0.7922
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5836 - accura

Testing datasets prediction result and output the accuracy

In [191]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

63/63 [==============================] - 0s 2ms/step


In [192]:
accuracy_score(y_test, y_pred)

0.8205